### ISSUE TITLE
这个有用吗？

### ISSUE THREAD

**Issue by Axure** [leancloud/leanengine-unit-test#2]
有一些文档失效了，比如 https://leancloud.cn/docs/cloud_code_commandline.html

**Comment by wujun4code** [comment]
新的地址是：https://leancloud.cn/docs/leanengine_cli.html

请收藏文档首页（https://leancloud.cn/docs/）可以随时关注文档的最新变动以及功能调整。




2016-06-14 12:19 GMT+08:00 Hu Zheng <notifications@github.com>:
